# Generated by Django 5.1 on 2024-08-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(null=True, upload_to='profiles_trainer/'),
        ),
    ]
