# Generated by Django 5.1 on 2024-09-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_historystudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historystudent',
            name='message',
            field=models.JSONField(null=True),
        ),
    ]
